# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M.xci
# IP: The module: 'PLL_12M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_12M'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_12M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_12M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M.xci
# IP: The module: 'PLL_12M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_12M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_12M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Work Files/EESDQ/Version1.3/vivado/ip/PLL_12M/PLL_12M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_12M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
